import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#002957",
        "primary": "#aac7ff",
        "on-surface-variant": "#c0c6d6",
        "surface-dim": "#10131b",
        "primary-fixed": "#d6e3ff",
        "on-surface": "#e0e2ed",
        "tertiary-container": "#eb6a12",
        "secondary-fixed-dim": "#aac7ff",
        "primary-fixed-dim": "#aac7ff",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#001b3e",
        "surface-container": "#1c2027",
        "surface-variant": "#31353d",
        "on-secondary-fixed-variant": "#264778",
        "error-container": "#93000a",
        "tertiary": "#ffb691",
        "outline-variant": "#414754",
        "on-secondary": "#083060",
        "surface-container-highest": "#31353d",
        "surface": "#10131b",
        "outline": "#8b91a0",
        "tertiary-fixed": "#ffdbcb",
        "surface-container-lowest": "#0b0e15",
        "primary-container": "#3e90ff",
        "on-tertiary-container": "#4a1b00",
        "inverse-surface": "#e0e2ed",
        "on-tertiary-fixed": "#341100",
        "on-primary": "#003064",
        "secondary-container": "#264778",
        "on-secondary-container": "#98b6ee",
        "inverse-primary": "#005db8",
        "background": "#10131b",
        "surface-tint": "#aac7ff",
        "surface-container-high": "#262a32",
        "surface-bright": "#363941",
        "tertiary-fixed-dim": "#ffb691",
        "secondary": "#aac7ff",
        "on-tertiary-fixed-variant": "#793100",
        "on-error": "#690005",
        "inverse-on-surface": "#2d3038",
        "on-background": "#e0e2ed",
        "surface-container-low": "#181c23",
        "secondary-fixed": "#d6e3ff",
        "on-primary-fixed": "#001b3e",
        "on-primary-fixed-variant": "#00468d",
        "on-tertiary": "#552000"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
