"""add E2EE messaging and followers

Revision ID: 782e8e16ed14
Revises: 0002_onboarding_fields
Create Date: 2026-07-30 03:32:13.444796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '782e8e16ed14'
down_revision = '0002_onboarding_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_messages_recipient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('user_follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_user_follows_follower_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name=op.f('fk_user_follows_following_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id', name=op.f('pk_user_follows'))
    )
    op.alter_column('ai_review_results', 'suggestions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_ai_review_results_pr_id', table_name='ai_review_results')
    op.create_index(op.f('ix_ai_review_results_pull_request_id'), 'ai_review_results', ['pull_request_id'], unique=False)
    op.alter_column('audit_logs', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('branches', 'is_protected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('branches', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_branches_repo_id', table_name='branches')
    op.create_index(op.f('ix_branches_repository_id'), 'branches', ['repository_id'], unique=False)
    op.alter_column('discussions', 'category',
               existing_type=postgresql.ENUM('general', 'ideas', 'qa', 'announcements', name='discussioncategory'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('discussions', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_discussions_repo_id', table_name='discussions')
    op.create_index(op.f('ix_discussions_repository_id'), 'discussions', ['repository_id'], unique=False)
    op.drop_index('ix_evt_user_id', table_name='email_verification_tokens')
    op.drop_constraint('uq_evt_token_hash', 'email_verification_tokens', type_='unique')
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.alter_column('issues', 'state',
               existing_type=postgresql.ENUM('open', 'closed', name='issuestate'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('issues', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_issues_repo_id', table_name='issues')
    op.create_index(op.f('ix_issues_repository_id'), 'issues', ['repository_id'], unique=False)
    op.alter_column('labels', 'color',
               existing_type=sa.VARCHAR(length=7),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_labels_repo_id', table_name='labels')
    op.create_index(op.f('ix_labels_repository_id'), 'labels', ['repository_id'], unique=False)
    op.alter_column('milestones', 'state',
               existing_type=postgresql.ENUM('open', 'closed', name='milestonestate'),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_milestones_repo_id', table_name='milestones')
    op.create_index(op.f('ix_milestones_repository_id'), 'milestones', ['repository_id'], unique=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_oauth_provider_account', 'oauth_accounts', type_='unique')
    op.create_table_comment(
        'oauth_accounts',
        'Unique constraint on (provider, provider_account_id) enforced in migration',
        existing_comment=None,
        schema=None
    )
    op.alter_column('organization_members', 'role',
               existing_type=postgresql.ENUM('owner', 'admin', 'member', name='organizationrole'),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_org_members_org_id', table_name='organization_members')
    op.drop_index('ix_org_members_user_id', table_name='organization_members')
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.drop_constraint('uq_organizations_name', 'organizations', type_='unique')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.alter_column('password_reset_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_prt_user_id', table_name='password_reset_tokens')
    op.drop_constraint('uq_prt_token_hash', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.alter_column('personal_access_tokens', 'scopes',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=None,
               existing_nullable=False)
    op.alter_column('personal_access_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_pat_token_hash', table_name='personal_access_tokens')
    op.drop_index('ix_pat_user_id', table_name='personal_access_tokens')
    op.drop_constraint('uq_pat_token_hash', 'personal_access_tokens', type_='unique')
    op.create_index(op.f('ix_personal_access_tokens_token_hash'), 'personal_access_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_personal_access_tokens_user_id'), 'personal_access_tokens', ['user_id'], unique=False)
    op.drop_index('ix_pr_comments_pr_id', table_name='pr_comments')
    op.create_index(op.f('ix_pr_comments_pull_request_id'), 'pr_comments', ['pull_request_id'], unique=False)
    op.drop_index('ix_pr_review_comments_pr_id', table_name='pr_review_comments')
    op.create_index(op.f('ix_pr_review_comments_pull_request_id'), 'pr_review_comments', ['pull_request_id'], unique=False)
    op.alter_column('pr_reviews', 'state',
               existing_type=postgresql.ENUM('pending', 'approved', 'changes_requested', 'commented', name='reviewstate'),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_pr_reviews_pr_id', table_name='pr_reviews')
    op.create_index(op.f('ix_pr_reviews_pull_request_id'), 'pr_reviews', ['pull_request_id'], unique=False)
    op.alter_column('pull_requests', 'state',
               existing_type=postgresql.ENUM('open', 'closed', 'merged', name='pullrequeststate'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pull_requests', 'is_draft',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_prs_repo_id', table_name='pull_requests')
    op.drop_index('ix_prs_state', table_name='pull_requests')
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_state'), 'pull_requests', ['state'], unique=False)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_refresh_tokens_token_hash', 'refresh_tokens', type_='unique')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.alter_column('repositories', 'visibility',
               existing_type=postgresql.ENUM('public', 'private', 'internal', name='repositoryvisibility'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'default_branch',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'is_fork',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'size_kb',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'star_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'fork_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'watcher_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('uq_repo_name_per_org_owner', table_name='repositories', postgresql_where='(owner_organization_id IS NOT NULL)')
    op.drop_index('uq_repo_name_per_user_owner', table_name='repositories', postgresql_where='(owner_user_id IS NOT NULL)')
    op.alter_column('repository_collaborators', 'permission',
               existing_type=postgresql.ENUM('read', 'triage', 'write', 'maintain', 'admin', name='permissionlevel'),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_repo_collab_repo_id', table_name='repository_collaborators')
    op.drop_index('ix_repo_collab_user_id', table_name='repository_collaborators')
    op.create_index(op.f('ix_repository_collaborators_repository_id'), 'repository_collaborators', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repository_collaborators_user_id'), 'repository_collaborators', ['user_id'], unique=False)
    op.drop_index('ix_repo_stars_repo_id', table_name='repository_stars')
    op.drop_index('ix_repo_stars_user_id', table_name='repository_stars')
    op.create_index(op.f('ix_repository_stars_repository_id'), 'repository_stars', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repository_stars_user_id'), 'repository_stars', ['user_id'], unique=False)
    op.drop_index('ix_repo_watchers_repo_id', table_name='repository_watchers')
    op.drop_index('ix_repo_watchers_user_id', table_name='repository_watchers')
    op.create_index(op.f('ix_repository_watchers_repository_id'), 'repository_watchers', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repository_watchers_user_id'), 'repository_watchers', ['user_id'], unique=False)
    op.drop_constraint('uq_ssh_keys_fingerprint', 'ssh_keys', type_='unique')
    op.drop_index('ix_ssh_keys_fingerprint', table_name='ssh_keys')
    op.create_index(op.f('ix_ssh_keys_fingerprint'), 'ssh_keys', ['fingerprint'], unique=True)
    op.alter_column('startup_collaboration_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'rejected', name='collaborationrequeststatus'),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_startup_collab_requests_requester_id', table_name='startup_collaboration_requests')
    op.drop_index('ix_startup_collab_requests_startup_id', table_name='startup_collaboration_requests')
    op.create_index(op.f('ix_startup_collaboration_requests_requester_user_id'), 'startup_collaboration_requests', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_startup_collaboration_requests_startup_id'), 'startup_collaboration_requests', ['startup_id'], unique=False)
    op.alter_column('startup_members', 'title',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('startup_open_roles', 'is_filled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('startups', 'stage',
               existing_type=postgresql.ENUM('idea', 'mvp', 'early_traction', 'growth', 'scaling', name='startupstage'),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_startups_slug', 'startups', type_='unique')
    op.drop_index('ix_startups_slug', table_name='startups')
    op.create_index(op.f('ix_startups_slug'), 'startups', ['slug'], unique=True)
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('maintainer', 'member', name='teamrole'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_repositories', 'permission',
               existing_type=postgresql.ENUM('read', 'triage', 'write', 'maintain', 'admin', name='permissionlevel'),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_team_repos_repo_id', table_name='team_repositories')
    op.drop_index('ix_team_repos_team_id', table_name='team_repositories')
    op.create_index(op.f('ix_team_repositories_repository_id'), 'team_repositories', ['repository_id'], unique=False)
    op.create_index(op.f('ix_team_repositories_team_id'), 'team_repositories', ['team_id'], unique=False)
    op.drop_index('ix_teams_org_id', table_name='teams')
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.add_column('users', sa.Column('public_key', sa.String(length=4000), nullable=True))
    op.alter_column('users', 'needs_onboarding',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('webhooks', 'events',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=None,
               existing_nullable=False)
    op.alter_column('webhooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_webhooks_repo_id', table_name='webhooks')
    op.create_index(op.f('ix_webhooks_repository_id'), 'webhooks', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_repository_id'), table_name='webhooks')
    op.create_index('ix_webhooks_repo_id', 'webhooks', ['repository_id'], unique=False)
    op.alter_column('webhooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('webhooks', 'events',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('users', 'two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'needs_onboarding',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'public_key')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.create_index('ix_teams_org_id', 'teams', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_team_repositories_team_id'), table_name='team_repositories')
    op.drop_index(op.f('ix_team_repositories_repository_id'), table_name='team_repositories')
    op.create_index('ix_team_repos_team_id', 'team_repositories', ['team_id'], unique=False)
    op.create_index('ix_team_repos_repo_id', 'team_repositories', ['repository_id'], unique=False)
    op.alter_column('team_repositories', 'permission',
               existing_type=postgresql.ENUM('read', 'triage', 'write', 'maintain', 'admin', name='permissionlevel'),
               server_default=sa.text("'read'::permissionlevel"),
               existing_nullable=False)
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('maintainer', 'member', name='teamrole'),
               server_default=sa.text("'member'::teamrole"),
               existing_nullable=False)
    op.drop_index(op.f('ix_startups_slug'), table_name='startups')
    op.create_index('ix_startups_slug', 'startups', ['slug'], unique=False)
    op.create_unique_constraint('uq_startups_slug', 'startups', ['slug'])
    op.alter_column('startups', 'stage',
               existing_type=postgresql.ENUM('idea', 'mvp', 'early_traction', 'growth', 'scaling', name='startupstage'),
               server_default=sa.text("'idea'::startupstage"),
               existing_nullable=False)
    op.alter_column('startup_open_roles', 'is_filled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('startup_members', 'title',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'Member'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_startup_collaboration_requests_startup_id'), table_name='startup_collaboration_requests')
    op.drop_index(op.f('ix_startup_collaboration_requests_requester_user_id'), table_name='startup_collaboration_requests')
    op.create_index('ix_startup_collab_requests_startup_id', 'startup_collaboration_requests', ['startup_id'], unique=False)
    op.create_index('ix_startup_collab_requests_requester_id', 'startup_collaboration_requests', ['requester_user_id'], unique=False)
    op.alter_column('startup_collaboration_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'rejected', name='collaborationrequeststatus'),
               server_default=sa.text("'pending'::collaborationrequeststatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_ssh_keys_fingerprint'), table_name='ssh_keys')
    op.create_index('ix_ssh_keys_fingerprint', 'ssh_keys', ['fingerprint'], unique=False)
    op.create_unique_constraint('uq_ssh_keys_fingerprint', 'ssh_keys', ['fingerprint'])
    op.drop_index(op.f('ix_repository_watchers_user_id'), table_name='repository_watchers')
    op.drop_index(op.f('ix_repository_watchers_repository_id'), table_name='repository_watchers')
    op.create_index('ix_repo_watchers_user_id', 'repository_watchers', ['user_id'], unique=False)
    op.create_index('ix_repo_watchers_repo_id', 'repository_watchers', ['repository_id'], unique=False)
    op.drop_index(op.f('ix_repository_stars_user_id'), table_name='repository_stars')
    op.drop_index(op.f('ix_repository_stars_repository_id'), table_name='repository_stars')
    op.create_index('ix_repo_stars_user_id', 'repository_stars', ['user_id'], unique=False)
    op.create_index('ix_repo_stars_repo_id', 'repository_stars', ['repository_id'], unique=False)
    op.drop_index(op.f('ix_repository_collaborators_user_id'), table_name='repository_collaborators')
    op.drop_index(op.f('ix_repository_collaborators_repository_id'), table_name='repository_collaborators')
    op.create_index('ix_repo_collab_user_id', 'repository_collaborators', ['user_id'], unique=False)
    op.create_index('ix_repo_collab_repo_id', 'repository_collaborators', ['repository_id'], unique=False)
    op.alter_column('repository_collaborators', 'permission',
               existing_type=postgresql.ENUM('read', 'triage', 'write', 'maintain', 'admin', name='permissionlevel'),
               server_default=sa.text("'read'::permissionlevel"),
               existing_nullable=False)
    op.create_index('uq_repo_name_per_user_owner', 'repositories', ['owner_user_id', 'name'], unique=True, postgresql_where='(owner_user_id IS NOT NULL)')
    op.create_index('uq_repo_name_per_org_owner', 'repositories', ['owner_organization_id', 'name'], unique=True, postgresql_where='(owner_organization_id IS NOT NULL)')
    op.alter_column('repositories', 'watcher_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('repositories', 'fork_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('repositories', 'star_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('repositories', 'size_kb',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('repositories', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('repositories', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('repositories', 'is_fork',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('repositories', 'default_branch',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'main'::character varying"),
               existing_nullable=False)
    op.alter_column('repositories', 'visibility',
               existing_type=postgresql.ENUM('public', 'private', 'internal', name='repositoryvisibility'),
               server_default=sa.text("'private'::repositoryvisibility"),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint('uq_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'])
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_pull_requests_state'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.create_index('ix_prs_state', 'pull_requests', ['state'], unique=False)
    op.create_index('ix_prs_repo_id', 'pull_requests', ['repository_id'], unique=False)
    op.alter_column('pull_requests', 'is_draft',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('pull_requests', 'state',
               existing_type=postgresql.ENUM('open', 'closed', 'merged', name='pullrequeststate'),
               server_default=sa.text("'open'::pullrequeststate"),
               existing_nullable=False)
    op.drop_index(op.f('ix_pr_reviews_pull_request_id'), table_name='pr_reviews')
    op.create_index('ix_pr_reviews_pr_id', 'pr_reviews', ['pull_request_id'], unique=False)
    op.alter_column('pr_reviews', 'state',
               existing_type=postgresql.ENUM('pending', 'approved', 'changes_requested', 'commented', name='reviewstate'),
               server_default=sa.text("'pending'::reviewstate"),
               existing_nullable=False)
    op.drop_index(op.f('ix_pr_review_comments_pull_request_id'), table_name='pr_review_comments')
    op.create_index('ix_pr_review_comments_pr_id', 'pr_review_comments', ['pull_request_id'], unique=False)
    op.drop_index(op.f('ix_pr_comments_pull_request_id'), table_name='pr_comments')
    op.create_index('ix_pr_comments_pr_id', 'pr_comments', ['pull_request_id'], unique=False)
    op.drop_index(op.f('ix_personal_access_tokens_user_id'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_token_hash'), table_name='personal_access_tokens')
    op.create_unique_constraint('uq_pat_token_hash', 'personal_access_tokens', ['token_hash'])
    op.create_index('ix_pat_user_id', 'personal_access_tokens', ['user_id'], unique=False)
    op.create_index('ix_pat_token_hash', 'personal_access_tokens', ['token_hash'], unique=False)
    op.alter_column('personal_access_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('personal_access_tokens', 'scopes',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_unique_constraint('uq_prt_token_hash', 'password_reset_tokens', ['token_hash'])
    op.create_index('ix_prt_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.alter_column('password_reset_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_unique_constraint('uq_organizations_name', 'organizations', ['name'])
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.create_index('ix_org_members_user_id', 'organization_members', ['user_id'], unique=False)
    op.create_index('ix_org_members_org_id', 'organization_members', ['organization_id'], unique=False)
    op.alter_column('organization_members', 'role',
               existing_type=postgresql.ENUM('owner', 'admin', 'member', name='organizationrole'),
               server_default=sa.text("'member'::organizationrole"),
               existing_nullable=False)
    op.drop_table_comment(
        'oauth_accounts',
        existing_comment='Unique constraint on (provider, provider_account_id) enforced in migration',
        schema=None
    )
    op.create_unique_constraint('uq_oauth_provider_account', 'oauth_accounts', ['provider', 'provider_account_id'])
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_milestones_repository_id'), table_name='milestones')
    op.create_index('ix_milestones_repo_id', 'milestones', ['repository_id'], unique=False)
    op.alter_column('milestones', 'state',
               existing_type=postgresql.ENUM('open', 'closed', name='milestonestate'),
               server_default=sa.text("'open'::milestonestate"),
               existing_nullable=False)
    op.drop_index(op.f('ix_labels_repository_id'), table_name='labels')
    op.create_index('ix_labels_repo_id', 'labels', ['repository_id'], unique=False)
    op.alter_column('labels', 'color',
               existing_type=sa.VARCHAR(length=7),
               server_default=sa.text("'#ededed'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_issues_repository_id'), table_name='issues')
    op.create_index('ix_issues_repo_id', 'issues', ['repository_id'], unique=False)
    op.alter_column('issues', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('issues', 'state',
               existing_type=postgresql.ENUM('open', 'closed', name='issuestate'),
               server_default=sa.text("'open'::issuestate"),
               existing_nullable=False)
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.create_unique_constraint('uq_evt_token_hash', 'email_verification_tokens', ['token_hash'])
    op.create_index('ix_evt_user_id', 'email_verification_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('ix_discussions_repository_id'), table_name='discussions')
    op.create_index('ix_discussions_repo_id', 'discussions', ['repository_id'], unique=False)
    op.alter_column('discussions', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('discussions', 'category',
               existing_type=postgresql.ENUM('general', 'ideas', 'qa', 'announcements', name='discussioncategory'),
               server_default=sa.text("'general'::discussioncategory"),
               existing_nullable=False)
    op.drop_index(op.f('ix_branches_repository_id'), table_name='branches')
    op.create_index('ix_branches_repo_id', 'branches', ['repository_id'], unique=False)
    op.alter_column('branches', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('branches', 'is_protected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_review_results_pull_request_id'), table_name='ai_review_results')
    op.create_index('ix_ai_review_results_pr_id', 'ai_review_results', ['pull_request_id'], unique=False)
    op.alter_column('ai_review_results', 'suggestions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.drop_table('user_follows')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
